title: "Aryan Archive"
description: "Quantitative approaches to cell and developmental biology"
url: "https://aryanboruah.github.io"
minimal_mistakes_skin: default
search: true
baseurl: ""



# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Aryan Boruah"
  avatar: "/assets/images/MSU_photo.jpg"
  bio: "Developing and applying mathematics for new biological understanding."
  location: "IISER TVM"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aryanboruah"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/aryanboruah/"

      
include:
  - _pages

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aryanboruah"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/aryanboruah/"
