title: "Aryan Archive"
description: "Quantitative approaches to dynamical systems in biology"
logo: "assets/images/simon-lee-eGALMCJ_Cvk-unsplash.jpg"
url: "https://aryanboruah.github.io"
minimal_mistakes_skin: default
search: true
baseurl: ""



# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"

head_scripts:
  - /assets/css/custom.css

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true

author:
  name: "Aryan Boruah"
  avatar: "/assets/images/MSU_Photo.jpg"
  bio: "Computational and Mathematical Modelling."
  location: "IISER TVM"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aryanboruah"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/aryanboruah/"

      
include:
  - _pages

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/aryanboruah"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/aryanboruah/"
